const express = require("express");
const Database = require("better-sqlite3");
const path = require("path");
const crypto = require("crypto");

const app = express();
const PORT = process.env.PORT || 3000;
const dataDir = path.join(__dirname, "data");
const fs = require("fs");
fs.mkdirSync(dataDir, { recursive: true });
const db = new Database(path.join(dataDir, "beg.sqlite"));

db.pragma("journal_mode = WAL");
db.exec(`
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,phone TEXT NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'customer',status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,description TEXT NOT NULL,minimum REAL NOT NULL,duration_days INTEGER NOT NULL,return_label TEXT NOT NULL,risk TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS investments (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,product_id INTEGER NOT NULL,principal REAL NOT NULL,earnings REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'ACTIVE',start_date TEXT NOT NULL,maturity_date TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE IF NOT EXISTS transactions (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,type TEXT NOT NULL,amount REAL NOT NULL,reference TEXT UNIQUE NOT NULL,status TEXT NOT NULL,description TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS withdrawals (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,amount REAL NOT NULL,phone TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'PENDING',reference TEXT UNIQUE NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
`);
function hash(p){return crypto.createHash("sha256").update(p).digest("hex")}
function ref(prefix){return prefix+"-"+Date.now().toString(36).toUpperCase()+"-"+crypto.randomBytes(3).toString("hex").toUpperCase()}
function userFromReq(req){const id=Number(req.headers["x-user-id"]);return id?db.prepare("SELECT id,name,email,phone,role,status FROM users WHERE id=?").get(id):null}
function requireUser(req,res,next){const u=userFromReq(req);if(!u)return res.status(401).json({error:"Please log in."});req.user=u;next()}
function requireAdmin(req,res,next){const u=userFromReq(req);if(!u||u.role!=="admin")return res.status(403).json({error:"Admin access required."});req.user=u;next()}
if(!db.prepare("SELECT COUNT(*) c FROM products").get().c){const ins=db.prepare("INSERT INTO products (name,description,minimum,duration_days,return_label,risk) VALUES (?,?,?,?,?,?)");ins.run("Starter","Entry-level investment product for eligible customers.",1000,30,"According to product terms","Capital is at risk.");ins.run("Growth","Longer-term product designed for customers seeking growth.",10000,90,"According to product terms","Capital is at risk.");ins.run("Premium","Higher minimum product for eligible customers.",50000,180,"According to product terms","Capital is at risk.")}
if(!db.prepare("SELECT COUNT(*) c FROM users").get().c){db.prepare("INSERT INTO users (name,email,phone,password_hash,role) VALUES (?,?,?,?,?)").run("Demo Customer","demo@betterearngain.test","0712345678",hash("Demo123!"),"customer");db.prepare("INSERT INTO users (name,email,phone,password_hash,role) VALUES (?,?,?,?,?)").run("Platform Admin","admin@betterearngain.test","0700000000",hash("Admin123!"),"admin")}
app.use(express.json());app.use(express.urlencoded({extended:true}));app.use(express.static(path.join(__dirname,"public")));
app.get("/health",(req,res)=>res.json({ok:true,service:"better-earn-gain-mvp"}));
app.post("/api/register",(req,res)=>{const{name,email,phone,password}=req.body;if(!name||!email||!phone||!password||password.length<8)return res.status(400).json({error:"Provide name, email, phone and a password of at least 8 characters."});try{const r=db.prepare("INSERT INTO users (name,email,phone,password_hash) VALUES (?,?,?,?)").run(name.trim(),email.toLowerCase().trim(),phone.trim(),hash(password));res.json({id:r.lastInsertRowid,message:"Account created. Demo KYC status is not enabled; production KYC must be implemented."})}catch(e){res.status(400).json({error:"Email is already registered."})}});
app.post("/api/login",(req,res)=>{const{email,password}=req.body;const u=db.prepare("SELECT id,name,email,phone,role,status FROM users WHERE email=? AND password_hash=?").get((email||"").toLowerCase().trim(),hash(password||""));if(!u)return res.status(401).json({error:"Invalid email or password."});res.json({user:u})});
app.get("/api/me",requireUser,(req,res)=>res.json({user:req.user}));
app.get("/api/products",(req,res)=>res.json({products:db.prepare("SELECT * FROM products WHERE active=1 ORDER BY id").all()}));
app.get("/api/dashboard",requireUser,(req,res)=>{const uid=req.user.id;const deposits=db.prepare("SELECT COALESCE(SUM(amount),0) x FROM transactions WHERE user_id=? AND type='DEPOSIT' AND status='COMPLETED'").get(uid).x;const invested=db.prepare("SELECT COALESCE(SUM(principal),0) x FROM investments WHERE user_id=? AND status='ACTIVE'").get(uid).x;const earnings=db.prepare("SELECT COALESCE(SUM(amount),0) x FROM transactions WHERE user_id=? AND type='EARNING' AND status='POSTED'").get(uid).x;const withdrawals=db.prepare("SELECT COALESCE(SUM(amount),0) x FROM withdrawals WHERE user_id=? AND status IN ('PENDING','COMPLETED')").get(uid).x;const available=Math.max(0,deposits+earnings-invested-withdrawals);const investments=db.prepare("SELECT i.*,p.name product_name FROM investments i JOIN products p ON p.id=i.product_id WHERE i.user_id=? ORDER BY i.id DESC").all(uid);const transactions=db.prepare("SELECT * FROM transactions WHERE user_id=? ORDER BY id DESC LIMIT 20").all(uid);res.json({balances:{deposits,invested,earnings,withdrawals,available},investments,transactions})});
app.post("/api/deposit/demo",requireUser,(req,res)=>{const amount=Number(req.body.amount);if(!Number.isFinite(amount)||amount<100)return res.status(400).json({error:"Minimum demo deposit is KES 100."});const reference=ref("MPESA-DEMO");db.prepare("INSERT INTO transactions (user_id,type,amount,reference,status,description) VALUES (?,?,?,?,?,?)").run(req.user.id,"DEPOSIT",amount,reference,"COMPLETED","Demo payment — no real money moved.");res.json({success:true,reference,message:"Demo deposit posted. This is not a real M-Pesa transaction."})});
app.post("/api/investments",requireUser,(req,res)=>{const product=db.prepare("SELECT * FROM products WHERE id=? AND active=1").get(Number(req.body.productId));const amount=Number(req.body.amount);if(!product)return res.status(404).json({error:"Product not found."});if(!Number.isFinite(amount)||amount<product.minimum)return res.status(400).json({error:`Minimum investment is KES ${product.minimum}.`});const deposits=db.prepare("SELECT COALESCE(SUM(amount),0) x FROM transactions WHERE user_id=? AND type='DEPOSIT' AND status='COMPLETED'").get(req.user.id).x;const invested=db.prepare("SELECT COALESCE(SUM(principal),0) x FROM investments WHERE user_id=? AND status='ACTIVE'").get(req.user.id).x;if(deposits-invested<amount)return res.status(400).json({error:"Insufficient available demo balance."});const start=new Date(),maturity=new Date(start.getTime()+product.duration_days*86400000);const r=db.prepare("INSERT INTO investments (user_id,product_id,principal,start_date,maturity_date) VALUES (?,?,?,?,?)").run(req.user.id,product.id,amount,start.toISOString(),maturity.toISOString());db.prepare("INSERT INTO transactions (user_id,type,amount,reference,status,description) VALUES (?,?,?,?,?,?)").run(req.user.id,"INVESTMENT",-amount,ref("INV"),"COMPLETED",`Investment in ${product.name}`);res.json({success:true,id:r.lastInsertRowid})});
app.get("/api/transactions",requireUser,(req,res)=>res.json({transactions:db.prepare("SELECT * FROM transactions WHERE user_id=? ORDER BY id DESC").all(req.user.id)}));
app.post("/api/withdrawals",requireUser,(req,res)=>{const amount=Number(req.body.amount),phone=(req.body.phone||req.user.phone).trim();if(!Number.isFinite(amount)||amount<100)return res.status(400).json({error:"Minimum withdrawal is KES 100."});const deposits=db.prepare("SELECT COALESCE(SUM(amount),0) x FROM transactions WHERE user_id=? AND type='DEPOSIT' AND status='COMPLETED'").get(req.user.id).x;const invested=db.prepare("SELECT COALESCE(SUM(principal),0) x FROM investments WHERE user_id=? AND status='ACTIVE'").get(req.user.id).x;const earnings=db.prepare("SELECT COALESCE(SUM(amount),0) x FROM transactions WHERE user_id=? AND type='EARNING' AND status='POSTED'").get(req.user.id).x;const pending=db.prepare("SELECT COALESCE(SUM(amount),0) x FROM withdrawals WHERE user_id=? AND status='PENDING'").get(req.user.id).x;const available=Math.max(0,deposits+earnings-invested-pending);if(amount>available)return res.status(400).json({error:"Insufficient available demo balance."});db.prepare("INSERT INTO withdrawals (user_id,amount,phone,status,reference) VALUES (?,?,?,?,?)").run(req.user.id,amount,phone,"PENDING",ref("WD"));res.json({success:true,message:"Withdrawal request submitted for admin review. No real money is sent in this MVP."})});
app.get("/api/admin/overview",requireAdmin,(req,res)=>{res.json({users:db.prepare("SELECT id,name,email,phone,role,status,created_at FROM users ORDER BY id DESC").all(),withdrawals:db.prepare("SELECT w.*,u.name,u.email FROM withdrawals w JOIN users u ON u.id=w.user_id ORDER BY w.id DESC").all(),investments:db.prepare("SELECT i.*,u.name user_name,p.name product_name FROM investments i JOIN users u ON u.id=i.user_id JOIN products p ON p.id=i.product_id ORDER BY i.id DESC").all()})});
app.post("/api/admin/withdrawals/:id",requireAdmin,(req,res)=>{const status=req.body.status;if(!["PENDING","COMPLETED","REJECTED"].includes(status))return res.status(400).json({error:"Invalid status."});const w=db.prepare("SELECT * FROM withdrawals WHERE id=?").get(Number(req.params.id));if(!w)return res.status(404).json({error:"Withdrawal not found."});db.prepare("UPDATE withdrawals SET status=? WHERE id=?").run(status,w.id);res.json({success:true})});
app.listen(PORT,()=>console.log(`Better Earn Gain running on port ${PORT}`));